import { defineArrayMember, defineField, defineType } from 'sanity';
import { requiredExternalUrl, requiredSlug } from '../helpers';

export const product = defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'The product URL segment. Generate it from the name, then review it.',
      options: { source: 'name', maxLength: 96 },
      validation: requiredSlug,
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Draft', value: 'draft' },
          { title: 'Active', value: 'active' },
          { title: 'Sold out', value: 'soldOut' },
          { title: 'Archived', value: 'archived' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required().max(240),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'array',
      of: [defineArrayMember({ type: 'block' })],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'displayPrice',
      title: 'Display price',
      type: 'number',
      description: 'Display-only USD price. Printful remains the checkout source of truth.',
      validation: (rule) => rule.required().positive().precision(2),
    }),
    defineField({
      name: 'primaryImage',
      title: 'Primary image',
      type: 'managedImage',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      of: [defineArrayMember({ type: 'managedImage' })],
      validation: (rule) => rule.max(12).unique(),
    }),
    defineField({
      name: 'color',
      title: 'Color',
      type: 'productColor',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      type: 'array',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'productCategory' }] })],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: 'collections',
      title: 'Collections',
      type: 'array',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'productCollection' }] })],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'printfulUrl',
      title: 'Printful product URL',
      type: 'url',
      description: 'Use the direct product page, not the Printful store homepage.',
      validation: requiredExternalUrl,
    }),
    defineField({ name: 'featured', title: 'Featured', type: 'boolean', initialValue: false }),
    defineField({ name: 'newArrival', title: 'New arrival', type: 'boolean', initialValue: false }),
    defineField({
      name: 'displayOrder',
      title: 'Display order',
      type: 'number',
      initialValue: 0,
      validation: (rule) => rule.required().integer().min(0),
    }),
    defineField({
      name: 'availableSizes',
      title: 'Available sizes',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
      validation: (rule) => rule.unique().max(20),
    }),
    defineField({
      name: 'careInstructions',
      title: 'Care instructions',
      type: 'array',
      of: [defineArrayMember({ type: 'block' })],
    }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo' }),
  ],
  orderings: [
    {
      title: 'Display order',
      name: 'displayOrderAsc',
      by: [{ field: 'displayOrder', direction: 'asc' }],
    },
    { title: 'Name', name: 'nameAsc', by: [{ field: 'name', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'name', status: 'status', price: 'displayPrice', media: 'primaryImage.image' },
    prepare: ({ title, status, price, media }) => ({
      title,
      subtitle: `${status ?? 'No status'} · ${typeof price === 'number' ? `$${price.toFixed(2)}` : 'No price'}`,
      media,
    }),
  },
});
